project:
  type: website
  output-dir: docs
  
website:
  title: "Bio806"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/tmkuras/Bio806.git
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Talia Kuras"

format:
  html:
    theme: minty
    toc: true

editor: source



